name: Build Python Project for macOS

on:
  push:
    branches:
      - master  # Запускать сборку при пуше в ветку main
  pull_request:
    branches:
      - master  # Запускать сборку при создании PR в ветку main

jobs:
  build:
    runs-on: macos-latest  # Используем MacOS для сборки

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Set up Python 3.11.3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.3'  # Указываем версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --name=TodoApp main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Используем v4
        with:
          name: TodoApp-MacOS
          path: dist/TodoApp  # Путь к собранному файлу